# Your account seed
account_seed:             ''

# Node url, leave empty for default node address ("wss://kusama.rpc.robonomics.network"), for local node use "ws://127.0.0.1:9944"
remote_node_url:          ''

# Type of your account, 'ED25519' or 'SR25519'
crypto_type:              ''

# An address of Robonomics subscription owner, empty if there is no subscription
rws_owner_address:        ''

# Full path of your directory, e.g. '/home/user/ipfs_files/', otherwise default path in ROS package will be used
ipfs_dir_path:            ''

# IPFS gateway to download files, e.g. 'https://ipfs.io'
ipfs_gateway:             ''

# API key from Pinata pinning service for IPFS
pinata_api_key:           ''

# Secret API key from Pinata pinning service for IPFS
pinata_api_secret_key:    ''